### ISSUE TITLE
Android: VideoPlayer does not render

### ISSUE THREAD

**Issue by barbaragomes** [shahen94/react-native-video-processing#136]
Hey there,

I've being using this library for a long time and it works perfectly for iOS.

The problem is that I can't get the VidePlayer to render on android. It doesn't log or throw any exception, I just can't see the video.

The Trimmer renders just fine.

I've tried pretty much all available releases but none of them work.
Is there any requirement that I'm missing?

I'm using react-native 0.41

Thank you

**Comment by barbaragomes** [comment]
Got it working.

Besides having to set the height of the VideoPlayer component, I have to mount the component with the property play=true

**Comment by shahen94** [comment]
Seems like that's a bug. Great that you could get it working.
I'll mark this as a bug. Thanks !

**Comment by gyetvan-andras** [comment]
It does not work for me too. It errors out on Android (on iOS works just fine) as follows:
`
java.lang.ClassCastException: com.shahenlibrary.VideoPlayer.VideoPlayerView cannot be cast to android.view.ViewGroup
	at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:320)
	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:180)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:819)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:926)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:47)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:986)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:892)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:628)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5763)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
`

**Comment by shahen94** [comment]
Hi @gyetvan-andras !
Probably you're trying to pass some child to VideoPlayer which doesn't support.

```
<VideoPlayer>
  <SomeChildHere />
</VideoPlayer>
```

**Comment by gyetvan-andras** [comment]
Yes, I have children for playback controls :) Thanks to point it out, this will be an easy fix. What makes me wonder, how does it work perfectly on iOS?

**Comment by shahen94** [comment]
iOS `ReactView` is completely different. 
You can pass everything as a child for every native component.

But on android - if we want our component to accept child component - our component should be extended from `ViewGroup` and not from `View`

https://github.com/shahen94/react-native-video-processing/blob/master/android/src/main/java/com/shahenlibrary/VideoPlayer/VideoPlayerView.java#L58

**Comment by gyetvan-andras** [comment]
Thanks for the clarification!

**Comment by gyetvan-andras** [comment]
Works like a charm after reorg. my UI. Big thanks for your guidance!
